# Generated by Django 5.2.17 on 2026-09-08 18:40

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'access_roles',
            },
        ),
        migrations.CreateModel(
            name='BrandData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('primary_color', models.CharField(blank=True, max_length=7, null=True)),
                ('secondary_color', models.CharField(blank=True, max_length=7, null=True)),
                ('accent_color', models.CharField(blank=True, max_length=7, null=True)),
                ('font_family', models.CharField(blank=True, max_length=150, null=True)),
                ('brand_style', models.CharField(blank=True, max_length=100, null=True)),
                ('background_style', models.CharField(blank=True, max_length=100, null=True)),
                ('raw_extraction_json', models.JSONField(blank=True, null=True)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Brand data',
                'db_table': 'brand_data',
            },
        ),
        migrations.CreateModel(
            name='CardCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('required_fields', models.JSONField()),
                ('default_aspect_ratio', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Card categories',
                'db_table': 'card_categories',
            },
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('tagline', models.CharField(blank=True, max_length=255, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('industry', models.CharField(blank=True, max_length=150, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('website', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Company info',
                'db_table': 'company_info',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='SocialLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedin', models.URLField(blank=True, max_length=500, null=True)),
                ('instagram', models.URLField(blank=True, max_length=500, null=True)),
                ('facebook', models.URLField(blank=True, max_length=500, null=True)),
                ('youtube', models.URLField(blank=True, max_length=500, null=True)),
                ('twitter_x', models.URLField(blank=True, max_length=500, null=True)),
                ('other_links', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Social links',
                'db_table': 'social_links',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='api.role')),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CardSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generating', 'Generating'), ('ready', 'Ready'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='api.cardcategory')),
            ],
            options={
                'db_table': 'card_sessions',
            },
        ),
        migrations.CreateModel(
            name='CardVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('generation_type', models.CharField(choices=[('initial', 'Initial'), ('edit', 'Edit'), ('regenerate', 'Regenerate')], max_length=20)),
                ('prompt_used', models.TextField(blank=True, null=True)),
                ('html_content', models.TextField()),
                ('ai_model_used', models.CharField(blank=True, max_length=100, null=True)),
                ('input_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('output_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('validation_passed', models.BooleanField(default=False)),
                ('validation_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='api.cardsession')),
            ],
            options={
                'db_table': 'card_versions',
            },
        ),
        migrations.AddField(
            model_name='cardsession',
            name='active_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_for_session', to='api.cardversion'),
        ),
        migrations.CreateModel(
            name='CardExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('png', 'PNG')], max_length=10)),
                ('file_path', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='api.cardversion')),
            ],
            options={
                'db_table': 'card_exports',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_url', models.URLField(max_length=500)),
                ('extraction_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('extraction_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand_data', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company', to='api.branddata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to=settings.AUTH_USER_MODEL)),
                ('view_access_roles', models.ManyToManyField(blank=True, db_table='company_view_access', related_name='companies', to='api.accessrole')),
                ('company_info', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company', to='api.companyinfo')),
                ('social_links', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company', to='api.sociallinks')),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'db_table': 'companies',
            },
        ),
        migrations.AddField(
            model_name='cardsession',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_sessions', to='api.company'),
        ),
        migrations.CreateModel(
            name='Offering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('product', 'Product'), ('service', 'Service'), ('key_offering', 'Key Offering'), ('category', 'Category')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='api.company')),
            ],
            options={
                'db_table': 'offerings',
            },
        ),
        migrations.CreateModel(
            name='PublishedCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_slug', models.SlugField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='published', to='api.cardversion')),
            ],
            options={
                'db_table': 'published_cards',
            },
        ),
        migrations.AddIndex(
            model_name='cardversion',
            index=models.Index(fields=['session'], name='card_versio_session_790a2b_idx'),
        ),
        migrations.AddConstraint(
            model_name='cardversion',
            constraint=models.UniqueConstraint(fields=('session', 'version_number'), name='uq_session_version'),
        ),
        migrations.AddIndex(
            model_name='cardexport',
            index=models.Index(fields=['version'], name='card_export_version_d8020b_idx'),
        ),
        migrations.AddIndex(
            model_name='cardsession',
            index=models.Index(fields=['company'], name='card_sessio_company_b1ed1e_idx'),
        ),
        migrations.AddIndex(
            model_name='offering',
            index=models.Index(fields=['company', 'type'], name='offerings_company_4947c4_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['user'], name='companies_user_id_c7db02_idx'),
        ),
    ]
