# Generated by Django 5.2.17 on 2026-09-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_master_audit_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='meta_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='cardcategory',
            name='meta_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='meta_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='companybrandpreference',
            name='meta_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='meta_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='meta_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
